CREATE TABLE CUSTOMER(
ID SERIAL PRIMARY KEY,
NAME TEXT,
ADDRESS TEXT);

CREATE TABLE ACCOUNT(
ID SERIAL PRIMARY KEY,
C_ID INTEGER REFERENCES CUSTOMER(ID),
MONEY);

CREATE TABLE TRANSACTION(
ID SERIAL PRIMARY KEY,
C_ID INTEGER REFERENCES CUSTOMER(ID),
A_ID INTEGER REFERENCES ACCOUNT(ID),
ACTION TEXT);
